//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTutorial1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class classicmodelsEntities : DbContext
    {
        public classicmodelsEntities()
            : base("name=classicmodelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customers> customers { get; set; }
        public DbSet<employees> employees { get; set; }
        public DbSet<offices> offices { get; set; }
        public DbSet<orderdetails> orderdetails { get; set; }
        public DbSet<orders> orders { get; set; }
        public DbSet<payments> payments { get; set; }
        public DbSet<productlines> productlines { get; set; }
        public DbSet<products> products { get; set; }
    }
}
