//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBTutorial1
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.orderdetails = new HashSet<orderdetails>();
        }
    
        public string productCode { get; set; }
        public string productName { get; set; }
        public string productLine { get; set; }
        public string productScale { get; set; }
        public string productVendor { get; set; }
        public string productDescription { get; set; }
        public short quantityInStock { get; set; }
        public double buyPrice { get; set; }
        public double MSRP { get; set; }
    
        public virtual ICollection<orderdetails> orderdetails { get; set; }
        public virtual productlines productlines { get; set; }
    }
}
